name: 'Enforce prettier'

on:
  push:
    branches:
      - main
      - testnet
      - develop
      - experimental
  pull_request:
    branches:
      - main
      - testnet
      - develop
      - experimental

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Prettier Check
        run: pnpm prettier:check
