name: 'Enforce prettier'

on:
  push:
    branches:
      - main
      - testnet
      - develop
      - experimental
  pull_request:
    branches:
      - main
      - testnet
      - develop
      - experimental

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --check deploy/**/*.ts test/**/*.ts scripts/**/*.ts
          dry: True
